apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: DeviceService
  name: DeviceService
  labels:
    app: DeviceService
spec:
  selector:
    matchLabels:
      app: DeviceService
  template:
    metadata:
      labels:
        app: DeviceService
        name: DeviceService
    spec:
      containers:
        - name: DeviceService
          image: mahendraintelops/ss_project/DeviceService
          imagePullPolicy: Always
          ports:
        
          - containerPort: 3004
            name: http
        
        
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            periodSeconds: 30
        