apiVersion: v1
kind: Service
metadata:
  namespace: DeviceService
  labels:
    app: DeviceService
  name: DeviceService
spec:
  ports:
  
    - protocol: TCP
      port: 3004
      targetPort: 3004
   
  selector:
    app: DeviceService
  type: ClusterIP
